apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: ethereum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:latest
        command: ["geth"]
        args:
        - "--datadir=/data"
        - "--config=/config/geth.toml"
        - "--nat=extip:208.67.222.222"
        - "--port=30303"
        - "--http"
        - "--http.addr=0.0.0.0"
        - "--http.port=8545"
        - "--http.vhosts=*"
        - "--http.corsdomain=*"
        - "--ws"
        - "--ws.addr=0.0.0.0"
        - "--ws.port=8546"
        - "--ws.origins=*"
        - "--authrpc.jwtsecret=/data/jwt.hex"
        - "--authrpc.addr=0.0.0.0"
        - "--authrpc.port=8551"
        - "--authrpc.vhosts=*"
        - "--metrics"
        - "--metrics.addr=0.0.0.0"
        - "--metrics.port=6060"
        ports:
        - name: http
          containerPort: 8545
        - name: p2p
          containerPort: 30303
        - name: ws
          containerPort: 8546
        - name: authrpc
          containerPort: 8551
        - name: metrics
          containerPort: 6060
        volumeMounts:
        - name: geth-data
          mountPath: /data
        - name: geth-config
          mountPath: /config
        - name: jwt-secret
          mountPath: /data/jwt.hex
          subPath: jwt.hex
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-pvc
      - name: geth-config
        configMap:
          name: geth-config
      - name: jwt-secret
        secret:
          secretName: prysm-jwt
