apiVersion: v1
kind: Service
metadata:
  name: geth-service
  namespace: ethereum
spec:
  type: LoadBalancer
  ports:
    - port: 30303
      targetPort: 30303
    - port: 8545
      targetPort: 8545
    - port: 8546
      targetPort: 8546
    - port: 8551
      targetPort: 8551
  selector:
    app: geth
