apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prysm-pvc
  namespace: ethereum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"  # Ensure this matches your cluster's storage class
